name              "cronjobs"
maintainer        "Abdulaziz AlShetwi"
maintainer_email  "aalshetwi@gmail.com"
license           "MIT"
description       "Sets or updates using the cron resource."
version           "1.0.0"